app_code: oneoaas-cmp
app_name: oneoaas-cmp
author: OneOaaS
date: 2017-04-10 11:38:23
introduction: OneOaaS CMP云管理社区版,是蓝鲸专用版,版权归OneOaaS所有
is_use_celery: true
language: python
libraries:
- name: requests
  version: 2.9.1
- name: pymysql
  version: 0.6.7
version: 1.0.0
